### ISSUE TITLE
Installation problem: RuntimeError: Could not read JSON repodata file

### ISSUE THREAD

**Issue by liangweiting-student** [chrisquince/STRONG#104]
My installation fails on "mamba env create -f conda_env.yaml". I have removed conda-forge from my channels in my ~/.condarc, but it didn't work. And then I've tried installing miniconda and mamba again, but it did not change anything. I got the following errors:

$ mamba env create -f conda_env.yaml
anaconda/noarch          [====================] (00m:00s) No change
bioconda/noarch          [====================] (00m:00s) No change
bioconda/linux-64        [====================] (00m:00s) No change
anaconda/linux-64        [====================] (00m:00s) No change
r/linux-64               [====================] (00m:00s) No change
r/noarch                 [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
ohmeta/noarch            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:00s) Done
ohmeta/linux-64          [====================] (00m:00s) No change
conda-forge/linux-64     [====================] (00m:02s) Done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/lib/python3.8/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(
      File "/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 135, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/pkgs/cache/976d321b.json) parse error line 17356

`$ /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/bin/mamba create -f conda_env.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/b
                          in/conda
             CONDA_PREFIX=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/b
                          in/python
               CONDA_ROOT=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/opt/gridengine/lib/lx-amd64:/opt/openmpi/lib:/opt/python/lib
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                     PATH=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/b
                          in:/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda
                          3/condabin:/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/m
                          iniconda3/bin:/ldfssz1/ST_META/share/User/zhujie/.conda/envs/bioenv/bi
                          n:/ldfssz1/ST_META/share/User/zhujie/.conda/envs/bioenv3.6/bin:/ldfssz
                          1/ST_META/share/User/zhujie/.conda/envs/bioenv2/bin:/ldfssz1/ST_META/s
                          hare/User/juyanmei/miniconda3/bin:/ldfssz1/ST_META/share/flow/biobaker
                          y-metaphlan2-d8ab9ca4244c:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/
                          local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bio/ncbi/
                          bin:/opt/bio/mpiblast/bin:/opt/bio/EMBOSS/bin:/opt/bio/clustalw/bin:/o
                          pt/bio/tcoffee/bin:/opt/bio/hmmer/bin:/opt/bio/phylip/exe:/opt/bio/mrb
                          ayes:/opt/bio/fasta:/opt/bio/glimmer/bin:/opt/bio/glimmer/scripts:/opt
                          /bio/gromacs/bin:/opt/bio/gmap/bin:/opt/bio/tigr/bin:/opt/bio/autodock
                          suite/bin:/opt/bio/wgs/bin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/jav
                          a/latest/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/condor/bin:/opt/condo
                          r/sbin:/opt/gridengine/bin/lx-amd64:/home/liangweiting/bin
       REQUESTS_CA_BUNDLE=<not set>
                    SPATH=/ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/stronginstal
                          l
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3
            shell level : 1
       user config file : /home/liangweiting/.condarc
 populated config files : /home/liangweiting/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.17
       base environment : /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/ohmeta/linux-64
                          https://conda.anaconda.org/ohmeta/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/pkgs
       envs directories : /ldfssz1/ST_META/P18Z10200N0127_GRJ/liangweiting/software/miniconda3/envs
                          /home/liangweiting/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/2.6.32-696.30.1.el6.x86_64 centos/6.9 glibc/2.17
                UID:GID : 1000590:2782
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by liangweiting-student** [comment]
I installed miniconda3 and mamba once again. This time I removed the ~/.condarc ~/.conda ~/.continum and anotationed conda setting in ~/.bashrc. I'm now able to progress in the install.
