### ISSUE TITLE
problem on SPAdes installation

### ISSUE THREAD

**Issue by yuxiangtan** [chrisquince/STRONG#113]
Dear author,

I was not able to install STRONG from the auto installer. I followed the manual installation step by step, but still failed on SPAdes ./build_cog_tools.sh . I install the SPAdes from conda, but in the dependency checking it looked at SPAdes/assembler/build_spades/bin/unitig-coverage, which is not part of the SPAdes package.

I have no idea what I can do now and I need you help on installation.

One suggestion, if you could provide a docker image which will be much easier for future users.

Thank you,

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Dear Yuxiang,

We use a particular version of SPAdes with tools allowing us to get high resolution assembly graph. That version of SPAdes is present in the repo and nothing will work well if you try to install some other SPAdes from, for instance, conda. 

The auto installer is just a small script which execute all the step from the "manual" installation. Hence, if the auto install doesn't work it's likely the manual one won't. 

When you say the auto install didn't work, can you expand on that? Can you share with me the corresponding error message so that I can help solve your issue?

Best,
Seb

**Comment by yuxiangtan** [comment]
Hi Sebastien,

Thank you for your reply. Attached are the logs. I could not figure our why it failed. That is why I install from conda, which as you said is not appropriate.

Honestly, since there are fixed version software, will it be possible to provide a docker image that everyone could easily use and avoid this kind of installation issues?

Best,

Yuxiang

[build_cog_tools.log](https://github.com/chrisquince/STRONG/files/7141126/build_cog_tools.log)
[install_strong.log](https://github.com/chrisquince/STRONG/files/7141127/install_strong.log)

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang,

I can see an issue in the compilation log, it seems like even though the zlib library is installed, you are missing the zlib.h header file. Unsure about what system you're working on but this would be fixed on ubuntu with:
`sudo apt-get -y install libbz2-dev libreadline-dev cmake g++ zlib1g zlib1g-dev`

Also, I can see that the path to zlib is : 
/home/tanyuxiang/.conda/envs/STRONG/lib/libz.so
It looks like it is inside of the conda env. I assume that you installed libz in conda only? 
Could you try having libbz2-dev libreadline-dev cmake g++ zlib1g zlib1g-dev installed system wide.

Then you would need to retry that step:
```
cd <path/to/strong>/STRONG/SPAdes/assembler
./build_cog_tools.sh 
```

I didn't answer you on the docker image the first time, for the simple reason that I don't know how to do that right now and this is not the most urgent thing I need to focus on at the moment. If we can't solve your issue, I may try and find time to do that.

Best,
Seb

**Comment by yuxiangtan** [comment]
[run.log](https://github.com/chrisquince/STRONG/files/7175095/run.log)

Hi Sebastien,

Thanks for all your reply and I found building a docker will be much easier way for me to solve it.
Now, I build a docker and pass all the check (SnakeNest/scripts/check_on_dependencies.py)

However, when I run your test data, I got two type of errors:
1. when I unzip the Test.tar.gz, it is truncated (I downloaded twice but all the same situation)
2. Although the dry run is same as the post with the Step #3 - Strain Decomposition error, I got more errors when I run the actual pipeline (possibly related to the error 1). The log attached.

So, how could I make sure the docker is correct? 

Once it is fully checked, I can upload the docker to dockerhub and share it will you.

Best,

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang

It's nice you managed to build a docker image which pass the checks.

1. Hum, strange, I can download/unzip perfectly fine. Either an issue with downloading or with unziping? Here is the md5, can you check yours? I hope the issue is on unzipping, because you can try doing it differently. If you can't manage to download the file, I'm unsure what could be done.
`3704340ce2ea5a268dae4cf1a6eaa171  Test.tar.gz`

2. yes, dryrun failing is normal, it is a sequential process and snakemake cannot anticipate what to do without previous steps output. Regarding spades, I had a look at the logs, and I can see that spades is failing though it is unclear why. Could you share/have a look at the file: assembly/spades.log. That's the log of spades and it will tell you why it's failing. If you do have truncated files, it's possible spades stop himself from difference in reads numbers between R1 and R2 files, or just malformed entries. So then it's just a matter of getting correct data. 

Well, if when creating a docker image your installation went without issue and the check tells you it's working, then I would say it is correct and works. 100% confidence would be achieved by being able to run 1 of the test dataset. 

Thanks for that, that would extremely helpful. 

Best,
Seb

**Comment by yuxiangtan** [comment]
Hi, Seb,

Yes, I created a docker image without issue and the check told me it's working. 
However, even if I checked the downloaded Test.tar.gz and checked the md5 and it is not truncated this time, the docker run still  ended with an error. (attached) 
[run.log](https://github.com/chrisquince/STRONG/files/7191267/run.log)

I push the docker to docker hub already: https://hub.docker.com/r/yuxiangtan/strong, maybe you can test is yourself as well. (The COG database is not within, users just need to point the path in the config.yaml as you mentioned in the github)

Best,

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang,

Cool, nice it worked. Ok, the log tell me it fails at creating a fig with an R script, though real log related to that script are for instance at:
results/Bin_2/tmp/haplotypes_tree.log
Can you tell me what's inside? Most likely a missing library, more troublesome would be an error message from lib version not being the right ones. 

Thanks a lot for that, I will have a go at testing it and documenting how to use it. 

Best,
Seb

**Comment by yuxiangtan** [comment]
Following are the error message, looks like a more troublesome one.

Warning message:
package 'tidyr' was built under R version 4.0.3
Warning message:
package 'stringr' was built under R version 4.0.5
Registered S3 method overwritten by 'treeio':
  method     from
  root.phylo ape
ggtree v2.4.1  For help: https://yulab-smu.top/treedata-book/

If you use ggtree in published research, please cite the most appropriate paper(s):

ESC[36m-ESC[39m Guangchuang Yu. Using ggtree to visualize data on tree-like structures. Current Protocols in Bioinformatics, 2020, 69:e96. doi:10.1002/cpbi.96
ESC[36m-ESC[39m Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping and visualizing associated data on phylogeny using ggtree. Molecular Biology and Evolution 2018, 35(12):3041-3043. doi:10.1093/molbev/msy194
ESC[36m-ESC[39m Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36. doi:10.1111/2041-210X.12628



Attaching package: 'ggtree'

The following object is masked from 'package:tidyr':

    expand

Warning message:
package 'ggtree' was built under R version 4.0.3
Warning message:
package 'ggplot2' was built under R version 4.0.5
Warning message:
package 'wesanderson' was built under R version 4.0.5
Error in DataMask$new(.data, caller_env) :
  argument "caller_env" is missing, with no default
Calls: ggtree ... mutate.data.frame -> mutate_cols -> <Anonymous> -> initialize
Execution halted

haplotypes_tree.log (END)

**Comment by yuxiangtan** [comment]
Hi, Seb

I run the test data for more than two week already, but it is still running and I found there was no resume option.
Also, I check the server is still running the job but using very little resources.

I am not sure what's happening now and what should I do. 
BTW, I need to restart the server in a few days.

Thank you!

Following is the log.

Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
all                             1              1              1
bed_orfs                        1              1              1
cat_split_annotation            1              1              1
compute_avg_cov                 1              1              1
concoct                         1              1              1
copy_fasta                      1              1              1
coverage                        1              1              1
create_bin_folders              1              1              1
cut_contigs                     1              1              1
extract_SCG_sequences           1              1              1
get_SCG_tables                  1              1              1
initial_quantity_of_bins        1              1              1
merge_contigs                   1              1              1
parse_cogs_annotation           1              1              1
prodigal                        1              1              1
reads_yaml                      1              1              1
refine                          1              1              1
rpsblast                      100              1              1
simplify                        1              1              1
spades                          1              1              1
split_fasta                     1              1              1
unitig_profiles                 1              1              1
total                         121              1              1

Select jobs to execute...

[Mon Sep 20 03:59:45 2021]
rule reads_yaml:
    output: samples.yaml
    jobid: 5
    resources: tmpdir=/tmp

[Mon Sep 20 03:59:46 2021]
Finished job 5.
1 of 121 steps (1%) done
Select jobs to execute...

[Mon Sep 20 03:59:46 2021]
rule coverage:
    output: profile/split/coverage.tsv
    jobid: 1
    resources: tmpdir=/tmp

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang,
From the logs it seems you've been running with only 1 core, that's something you can change. Then it would be faster :)
There is a resume function. This pipeline is written with snakemake, a workflow management system, which check what's left to run and schedule tasks automatically. So, what's happening exactly? You are relaunching STRONG with the same exact config file and it restart from scratch? That should not happen.... You can try using the option -s -t, which asks snakemake to go through the whole workflow and update timestamps. Since snakemake also check timestamp consistency when deciding what needs to be rerun. Example: file needed for a task is more recent than output of the task, then the task need to be rerun. 
I am still looking at that issue with R library and will answer you shortly.
Best,
Seb

**Comment by yuxiangtan** [comment]
Hi Seb,

OK, I thought I set the core number in the config file. I tried 30 core again, and it finished the spade step now. However, it broke at step 1, which I have no idea what I could do.

Following is the key error message and the full log file attached.
Step #1 - Assembly / Binning / COG Annotation
Traceback (most recent call last):
  File "/STRONG/bin//STRONG", line 94, in <module>
    call_snake(["--snakefile", "SnakeNest/SCogSubGraph.snake"])
  File "/STRONG/bin//STRONG", line 83, in call_snake
    subprocess.check_call(base_params + extra_params, stdout=sys.stdout, stderr=sys.stderr)
  File "/root/miniconda3/envs/STRONG/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['snakemake', '--directory', '/data/Xianjinyuan/tanyuxiang/FMT_mouse-WY/STRONG_all/rerun2', '--cores', '30', '--config', 'LOCAL_DIR=/STRONG', '--configfile=/data/Xianjinyuan/tanyuxiang/FMT_mouse-WY/STRONG_all/rerun2/config.yaml', '--latency-wait', '120', '-k', '--snakefile', 'SnakeNest/SCogSubGraph.snake']' returned non-zero exit status 1.

[run.log](https://github.com/chrisquince/STRONG/files/7369503/run.log)

Best,

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang,
Can you share the file at :  `profile/assembly/index.log`
That would be where the error message would be stored.
Best,
Seb

**Comment by yuxiangtan** [comment]
Hi, Seb,

I ran a new test on a very small set of simulation test data. 

However, I still got error and not able to go through the whole process. (run.log attached)
[run.log](https://github.com/chrisquince/STRONG/files/7743141/run.log)

Up till now, I only successfully ran the whole pipeline on the provided test data, but all failed in other datasets.
I am not sure what to do now, and I am not sure whether the docker I built is ready for public in this case.

Best,

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Hi Yuxiang, 
Sorry for the lack of answer previously, as your issue takes more time to solve I need to secure some on my schedule and never got around to do so. 
From a quick look at your log, that is linked to running gtdb. I updated the STRONG not too long ago to deal whith this particular issue of locating gtdb reference genome. I may need to pin version in the conda env, so that these don't occur in the futur.
Please have a go at using latest version of STRONG and tell me how it goes.
Cheers,
Seb

**Comment by yuxiangtan** [comment]
Hi Seb, 

I pulled the code and it fixed the gtdb problem

But I got a new problem at the plot_tree_fig step. Log attached.

[run.log](https://github.com/chrisquince/STRONG/files/7755609/run.log)

Best,

Yuxiang

**Comment by yuxiangtan** [comment]
Hi @Sebastien-Raguideau ,

Any update about this since then?
I updated the previous fixes in docker v1. 

Best,

Yuxiang
